{{- if .Values.serviceAccount.openshift.scc.create -}}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "cortex-xdr.fullname" . }}-{{ .Values.namespace.name }}
allowHostDirVolumePlugin: true
allowPrivilegedContainer: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowedCapabilities:
  - SYS_ADMIN
  - SYSLOG
  - SYS_CHROOT
  - SYS_MODULE
  - SYS_PTRACE
  - SYS_RESOURCE
  - SYS_RAWIO
  - DAC_OVERRIDE
  - DAC_READ_SEARCH
  - NET_ADMIN
  - NET_RAW
  - IPC_LOCK
  - FOWNER
  - KILL
  - SETGID
  - SETUID
fsGroup:
  type: RunAsAny
groups: []
priority: 0
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:{{ .Values.namespace.name }}
  - system:serviceaccount:{{ .Values.namespace.name }}:{{ include "cortex-xdr.serviceAccountName" . }}
volumes:
  - downwardAPI
  - hostPath
  - secret
{{- end }}
